### ISSUE TITLE
Integrate spree_social

### ISSUE THREAD

**Issue by joshnuss** [sprangular/sprangular#23]
Refactor into separate controller

**Comment by joshnuss** [comment]
This should be its own gem, called "sprangular_social"

**Comment by joshnuss** [comment]
Instructions for integrating spree_social: https://github.com/sprangular/sprangular/wiki/OAuth-Integration

**Comment by ninjz** [comment]
I do the setup with spree_social but i'm getting 'No route matches [GET] "/users/auth/facebook/callback" ' After logging in to facebook

**Comment by joshnuss** [comment]
Hi @ninjz 

Did you follow the setup steps in spree_social's README? Like setting up a Spree::AuthenticationMethod?

**Comment by joshnuss** [comment]
Also, you can verify if the route exists by running:

```shell
rake routes | grep auth
```

**Comment by FadliKun** [comment]
i got the same error with you Mr @ninjz , do u have the solution?

when i `rake routes | grep auth` just like Mr @joshnuss said, the routes is exist, but i just don't know why it's keep show   `No route matches [GET] "/users/auth/facebook/callback"`

this is the routes: 

`spree_user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                                             spree/omniauth_callbacks#passthru {:provider=>/facebook|twitter|github|google_oauth2|amazon/}`
                     
`spree_user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)                                      spree/omniauth_callbacks#:action`

is it because the frontend routes between angular and spree different ?

thanks...

**Comment by FadliKun** [comment]
Mr @joshnuss is sprangular still developed ?
